name: 'GitHub Actions Variable Groups'
author: 'Brett Logan'
description: 'Allows for the central management of environment variables across multiple GitHub Actions workflows'
inputs:
  groups:
    description: A list of variable group files or directories containing variable group files.
    required: true
  org:
    description: The GitHub org containing where the repo is hosted.
    required: true
    default: ${{ github.repository_owner }}
  repo:
    description: The repo where the GitHub files under groups are hosted.
    required: true
  token:
    description: GitHub PAT used to access the repo.
    required: true
    default: ${{ github.token }}
branding:
  icon: align-left
  color: purple
runs:
  using: node16
  main: dist/index.js
